//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kutuphane.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _1f65326843961df0de46631c56b08e21 {
            get {
                object obj = ResourceManager.GetObject("1f65326843961df0de46631c56b08e21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _1f65326843961df0de46631c56b08e211 {
            get {
                object obj = ResourceManager.GetObject("1f65326843961df0de46631c56b08e211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _2ae7ede073c1080482435f34f81ff66f {
            get {
                object obj = ResourceManager.GetObject("2ae7ede073c1080482435f34f81ff66f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _2ae7ede073c1080482435f34f81ff66f1 {
            get {
                object obj = ResourceManager.GetObject("2ae7ede073c1080482435f34f81ff66f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _2ae7ede073c1080482435f34f81ff66f2 {
            get {
                object obj = ResourceManager.GetObject("2ae7ede073c1080482435f34f81ff66f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _41168532abf589e17e34d03759e2afb4 {
            get {
                object obj = ResourceManager.GetObject("41168532abf589e17e34d03759e2afb4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _5c856665da4aa1d8a5771c2aed0ed1dc {
            get {
                object obj = ResourceManager.GetObject("5c856665da4aa1d8a5771c2aed0ed1dc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _5c856665da4aa1d8a5771c2aed0ed1dc1 {
            get {
                object obj = ResourceManager.GetObject("5c856665da4aa1d8a5771c2aed0ed1dc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _5c856665da4aa1d8a5771c2aed0ed1dc2 {
            get {
                object obj = ResourceManager.GetObject("5c856665da4aa1d8a5771c2aed0ed1dc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _5fda94df8ce8762a240497314c72372d {
            get {
                object obj = ResourceManager.GetObject("5fda94df8ce8762a240497314c72372d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _7f210f3a0ee4d7cd35ef2546ff0dffdb {
            get {
                object obj = ResourceManager.GetObject("7f210f3a0ee4d7cd35ef2546ff0dffdb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _8ab6acfcee1b3724525ddfc0951f3441 {
            get {
                object obj = ResourceManager.GetObject("8ab6acfcee1b3724525ddfc0951f3441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _93357f11e741a56e43c87d56c41ee10d {
            get {
                object obj = ResourceManager.GetObject("93357f11e741a56e43c87d56c41ee10d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _93357f11e741a56e43c87d56c41ee10d1 {
            get {
                object obj = ResourceManager.GetObject("93357f11e741a56e43c87d56c41ee10d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _97ee70d21ac1e17af8ab3c349239adea {
            get {
                object obj = ResourceManager.GetObject("97ee70d21ac1e17af8ab3c349239adea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _97ee70d21ac1e17af8ab3c349239adea1 {
            get {
                object obj = ResourceManager.GetObject("97ee70d21ac1e17af8ab3c349239adea1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap a_peaceful_library_with_a_variety_of_books_on_the_shelves_wallpaper_2880x1800_8 {
            get {
                object obj = ResourceManager.GetObject("a-peaceful-library-with-a-variety-of-books-on-the-shelves-wallpaper-2880x1800_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ad1079e808bfccd0075d47dd975e1957 {
            get {
                object obj = ResourceManager.GetObject("ad1079e808bfccd0075d47dd975e1957", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ad1079e808bfccd0075d47dd975e19571 {
            get {
                object obj = ResourceManager.GetObject("ad1079e808bfccd0075d47dd975e19571", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ad1079e808bfccd0075d47dd975e19572 {
            get {
                object obj = ResourceManager.GetObject("ad1079e808bfccd0075d47dd975e19572", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ad1079e808bfccd0075d47dd975e19573 {
            get {
                object obj = ResourceManager.GetObject("ad1079e808bfccd0075d47dd975e19573", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap c86a443d91cfdc8202c2878d290b771f {
            get {
                object obj = ResourceManager.GetObject("c86a443d91cfdc8202c2878d290b771f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap c86a443d91cfdc8202c2878d290b771f1 {
            get {
                object obj = ResourceManager.GetObject("c86a443d91cfdc8202c2878d290b771f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap c86a443d91cfdc8202c2878d290b771f2 {
            get {
                object obj = ResourceManager.GetObject("c86a443d91cfdc8202c2878d290b771f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap c86a443d91cfdc8202c2878d290b771f3 {
            get {
                object obj = ResourceManager.GetObject("c86a443d91cfdc8202c2878d290b771f3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap c86a443d91cfdc8202c2878d290b771f4 {
            get {
                object obj = ResourceManager.GetObject("c86a443d91cfdc8202c2878d290b771f4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap c86a443d91cfdc8202c2878d290b771f5 {
            get {
                object obj = ResourceManager.GetObject("c86a443d91cfdc8202c2878d290b771f5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kapak_fotosu {
            get {
                object obj = ResourceManager.GetObject("kapak-fotosu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kutuphane0 {
            get {
                object obj = ResourceManager.GetObject("kutuphane0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kutuphane01 {
            get {
                object obj = ResourceManager.GetObject("kutuphane01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_an_old_style_library_with_shelves_full_of_books_image_2679112 {
            get {
                object obj = ResourceManager.GetObject("pngtree-an-old-style-library-with-shelves-full-of-books-image_2679112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_an_old_style_library_with_shelves_full_of_books_image_26791121 {
            get {
                object obj = ResourceManager.GetObject("pngtree-an-old-style-library-with-shelves-full-of-books-image_26791121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_an_old_style_library_with_shelves_full_of_books_image_26791122 {
            get {
                object obj = ResourceManager.GetObject("pngtree-an-old-style-library-with-shelves-full-of-books-image_26791122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
